### PR TITLE
Add an utils

### PR DESCRIPTION
**Pull request by itscheems**
More convenient receiving parameters.

### CODE REVIEW

**Comment by jamezp** [comment]
We cannot add utilities here. Additions like this need to go through the [Jakarta EE Specification Process](https://jakarta.ee/about/jesp/).

This is meant to be a fork of the spec with fixes only for CVE's and other security fixes. The API is changed from the upstream specification.

**Comment by itscheems** [comment]
Thanks, I'll go and look it up. I love open source and would love to contribute to some open source frameworks! Hopefully I can make some contributions.

**Comment by jamezp** [comment]
There are plenty of open source projects so I'm sure you'll be able to find something :)

**Comment by itscheems** [comment]
I see.  O(∩_∩)O~

**Pull request closed without merging**
